nodeLinker: node-modules

npmScopes:
  olxbr:
    npmRegistryServer: "http://nexus.olxbr.io/repository/olx-npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist:
  - "*.olxbr.io"

enableStrictSsl: false

yarnPath: .yarn/releases/yarn-3.2.1.cjs
