version: '3.9'

services:
  app:
    image: node:20-alpine3.20
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json
      - ./packages:/app/packages
      - ./yarn.lock:/app/yarn.lock
      - ./tsconfig.json:/app/tsconfig.json
      - ./node_modules:/app/node_modules
    command: sh -c "yarn install && cd /app && yarn workspace @sprint-review/client start:prod"
    env_file:
      - .env
